version: "3"

services:
  api:
    container_name: api
    build: .
    restart: always
    environment:
      DB_HOST: blog-host
      DB_USERNAME: test
      DB_PASSWORD: test
      DB_NAME: blogs

    volumes:
      - .:/app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - back-notused:/app/node_modules
    ports:
      - 5200:5000
    networks:
      - devster
    depends_on:
      - blog-host
    links:
      - blog-host

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - devster
    

  blog-host:
    container_name: blog-host
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: blogs
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3344:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - devster

  mytest-phpmyadmin:
    container_name: mytest-phpmyadmin
    image: phpmyadmin
    environment:
      PMA_HOST: blog-host
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8050:80
    networks:
      - devster

networks:
  devster:
    driver: bridge
volumes:
  dbdata:
  back-notused: