name: Deploy to DigitalOcean

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@157.230.250.113 << 'EOF'
          cd /var/www/backend/blogs
          git pull origin production
          npm install
          pm2 restart blog || pm2 start src/server.js --name blog
          EOF
